name: Build and Publish image to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: programmingroup
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
      - name: Build and push Docker image
        run: |
          docker build . -t programmingroup/my-profile-lgonzalez:latest
          docker push programmingroup/my-profile-lgonzalez:latest
